# Module 3
#   Programming Assignment 4
#     Prob-5.py

# <YOUR NAME>

def main():
    try:
        x = eval(2)
        print("x:", x)
    except:
        print("There was an error within the eval function, exiting")
        exit


   



main()